# -*- coding: utf-8 -*-
"""serise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQgpB02teEV-KPi2KgIDiMWNlkeiDYM4
"""

#create empty serise
import pandas as pd

a = pd.Series()
print(a)



#Create a Series from ndarray
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
# b = pd.Series(data)
b = pd.Series(data,index=[100,202,303,404])
 
print(b)

#Create a Series from dict

import pandas as pd
import numpy as np
data = {'d':12,'e':123, 'a':2,'c':9}
#b = pd.Series(data)
aja = pd.Series(data,index['a','b','c','e','d'])
print(aja)

import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve the first element
print (s[2])

